"""making reviews work

Revision ID: 189a895bdeed
Revises: e1273c28ddea
Create Date: 2025-05-13 12:39:21.048782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189a895bdeed'
down_revision = 'e1273c28ddea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('review_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
