"""add nullable imageUrl to menuItem

Revision ID: cb759dad9439
Revises: d1b5d2affb15
Create Date: 2025-05-09 19:48:07.241570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb759dad9439'
down_revision = 'd1b5d2affb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
